import { StyleSheet } from "react-native";
import { Border, Color, FontFamily, FontSize } from "../GlobalStyles";




const styles = StyleSheet.create({
    groupLayout: {
      height: 50,
      width: 300,
      left: 45,
      position: "absolute",
    },
    profileLayout: {
      height: 24,
      position: "absolute",
    },
    usernameTypo: {
      width: 115,
      textAlign: "left",
      color: Color.colorSilver_100,
      fontSize: FontSize.size_mini,
      fontFamily: FontFamily.lato,
      position: "absolute",
    },
    vectorIconLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    emailIconPosition: {
      width: 14,
      left: 18,
      position: "absolute",
    },
    rectangleLayout: {
      width: 56,
      height: 34,
      position: "absolute",
    },
    facebookLayout: {
      height: 35,
      position: "absolute",
    },
    iconPosition: {
      top: "0%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    createAccount: {
      top: 166,
      left: 92,
      fontSize: 30,
      width: 206,
      height: 41,
      textAlign: "center",
      color: Color.colorGray,
      fontFamily: FontFamily.lato,
      fontWeight: "700",
      position: "absolute",
    },
    groupShadowBox: {
      borderRadius: Border.br_21xl,
      shadowOpacity: 1,
      elevation: 20,
      shadowRadius: 20,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowColor: "rgba(0, 0, 0, 0.1)",
      left: 0,
      top: 0,
      height: 50,
      width: 300,
      position: "absolute",
      backgroundColor: Color.colorWhite,
    },
    backIcon: {
      position: 'absolute',
      zIndex: 10, 
      top: 70,
      left: 20,
      
  },
    profileIcon: {
      width: 24,
      left: 0,
      top: 0,
      overflow: "hidden",
    },
    username: {
      top: 3,
      left: 27,
      height: 18,
    },
    profileParent: {
      top: 13,
      left: 14,
      width: 143,
    },
    rectangleParent: {
      top: 249,
    },
    vectorIcon: {
      height: "35%",
      width: "4.67%",
      top: "28%",
      right: "89.33%",
      bottom: "37%",
      left: "6%",
    },
    password: {
      top: 14,
      height: 17,
      left: 45,
      width: 115,
      textAlign: "left",
      color: Color.colorSilver_100,
    },
    rectangleGroup: {
      top: 341,
    },
    emailIcon: {
      top: 19,
      height: 11,
      overflow: "hidden",
    },
    rectangleContainer: {
      top: 433,
    },
    groupChild1: {
      top: 15,
      borderRadius: 3,
      backgroundColor: "#9a9a9a",
      height: 20,
    },
    groupView: {
      top: 525,
    },
    orCreateAccount: {
      top: 700,
      left: 68,
      width: 254,
      fontSize: FontSize.size_mini,
      height: 24,
      textAlign: "center",
      color: Color.colorGray,
      fontFamily: FontFamily.lato,
      position: "absolute",
    },
    create: {
      left: 201,
      fontSize: FontSize.size_6xl,
      width: 88,
      height: 34,
      top: 627,
      textAlign: "left",
      color: Color.colorGray,
      fontFamily: FontFamily.lato,
      fontWeight: "700",
      position: "absolute",
    },
    rectangleLineargradient: {
      borderRadius: Border.br_mid,
      backgroundColor: "transparent",
      left: 0,
      top: 0,
    },
    vectorIcon1: {
      height: "52.94%",
      width: "32.14%",
      top: "23.53%",
      right: "33.93%",
      bottom: "23.53%",
      left: "33.93%",
    },
    rectangleParent1: {
      left: 289,
      top: 627,
      width: 56,
    },
    signupChild: {
      left: -203,
      width: 391,
      height: 119,
      top: 0,
      position: "absolute",
    },
    signupItem: {
      top: 556,
      left: 69,
      width: 2,
      height: 2,
      position: "absolute",
    },
    signupInner: {
      top: 542,
      left: 65,
      borderRadius: 1,
      width: 10,
      height: 12,
      position: "absolute",
      backgroundColor: Color.colorWhite,
    },
    facebookIcon: {
      width: 35,
      left: 0,
      top: 0,
    },
    twitterIcon: {
      height: "99.72%",
      width: "23.18%",
      right: "40.4%",
      bottom: "0.28%",
      left: "36.42%",
    },
    googleIcon: {
      height: "100%",
      width: "23.25%",
      right: "3.91%",
      bottom: "0%",
      left: "72.85%",
    },
    facebookParent: {
      top: 736,
      left: 119,
      width: 151,
    },
    signupChild1: {
      top: 599,
      left: -267,
      width: 415,
      height: 363,
      position: "absolute",
    },
    signup: {
      flex: 1,
      width: "100%",
      height: 844,
      overflow: "hidden",
      backgroundColor: Color.colorWhite,
    },
  });

  export default styles;